// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#include "ui.h"

void changeWifi(lv_event_t * e)
{
	// Your code here
}
