// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_Chat = NULL;
lv_obj_t * ui_Chat_container = NULL;
lv_obj_t * ui_Chat_date = NULL;
lv_obj_t * ui_C1 = NULL;
lv_obj_t * ui_Chat_Panel1 = NULL;
lv_obj_t * ui_Chat1 = NULL;
lv_obj_t * ui_Chat_Icon1 = NULL;
lv_obj_t * ui_C2 = NULL;
lv_obj_t * ui_Chat_Panel2 = NULL;
lv_obj_t * ui_Chat2 = NULL;
lv_obj_t * ui_Chat_Icon2 = NULL;
lv_obj_t * ui_Scrolldots2 = NULL;
// event funtions
void ui_event_Chat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_Chat_date, 100);
        upanim_Animation(ui_C1, 200);
        upanim_Animation(ui_C2, 300);
        scrolldot_Animation(ui_Scrolldots2, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Clock_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Music_Player, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Music_Player_screen_init);
    }
}

// build funtions

void ui_Chat_screen_init(void)
{
    ui_Chat = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Chat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Chat, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_Chat, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chat_container = lv_obj_create(ui_Chat);
    lv_obj_remove_flag(ui_Chat_container, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_width(ui_Chat_container, lv_pct(97));
    lv_obj_set_height(ui_Chat_container, lv_pct(96));
    lv_obj_set_x(ui_Chat_container, 0);
    lv_obj_set_y(ui_Chat_container, -1);
    lv_obj_set_align(ui_Chat_container, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Chat_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chat_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chat_date = ui_Small_Label_create(ui_Chat_container);
    lv_obj_set_x(ui_Chat_date, 0);
    lv_obj_set_y(ui_Chat_date, 2);
    lv_obj_set_align(ui_Chat_date, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Chat_date, "Yesterday 07:25 PM");
    lv_obj_set_style_text_color(ui_Chat_date, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chat_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chat_date, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_C1 = lv_obj_create(ui_Chat_container);
    lv_obj_set_height(ui_C1, 109);
    lv_obj_set_width(ui_C1, lv_pct(95));
    lv_obj_set_x(ui_C1, -12);
    lv_obj_set_y(ui_C1, 23);
    // lv_obj_remove_flag(ui_C1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_C1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_C1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_C1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_C1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_C1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_C1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chat_Panel1 = lv_obj_create(ui_C1);
    lv_obj_set_width(ui_Chat_Panel1, 169);
    lv_obj_set_height(ui_Chat_Panel1, 97);
    lv_obj_set_x(ui_Chat_Panel1, 5);
    lv_obj_set_y(ui_Chat_Panel1, 1);
    lv_obj_remove_flag(ui_Chat_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Chat_Panel1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Chat_Panel1, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chat_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Chat_Panel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Chat_Panel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Chat_Panel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Chat_Panel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chat1 = ui_Small_Label_create(ui_Chat_Panel1);
    lv_obj_set_width(ui_Chat1, lv_pct(100));
    lv_obj_set_height(ui_Chat1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Chat1, 0);
    lv_obj_set_y(ui_Chat1, 0);
    lv_obj_set_align(ui_Chat1, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_Chat1, "Xin chào");
    lv_obj_set_style_text_color(ui_Chat1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chat1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chat1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chat_Icon1 = lv_image_create(ui_C1);
    lv_image_set_src(ui_Chat_Icon1, &ui_img_chatbox_png);
    lv_obj_set_width(ui_Chat_Icon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Chat_Icon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Chat_Icon1, 0);
    lv_obj_set_y(ui_Chat_Icon1, 94);
    lv_obj_add_flag(ui_Chat_Icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Chat_Icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Chat_Icon1, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Chat_Icon1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_C2 = lv_obj_create(ui_Chat_container);
    lv_obj_set_height(ui_C2, 106);
    lv_obj_set_width(ui_C2, lv_pct(99));
    lv_obj_set_x(ui_C2, 3);
    lv_obj_set_y(ui_C2, 129);
    // lv_obj_remove_flag(ui_C2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_C2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_C2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_C2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_C2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_C2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_C2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chat_Panel2 = lv_obj_create(ui_C2);
    lv_obj_set_width(ui_Chat_Panel2, 169);
    lv_obj_set_height(ui_Chat_Panel2, 86);
    lv_obj_set_x(ui_Chat_Panel2, -6);
    lv_obj_set_y(ui_Chat_Panel2, -1);
    lv_obj_set_align(ui_Chat_Panel2, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Chat_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Chat_Panel2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Chat_Panel2, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chat_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Chat_Panel2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Chat_Panel2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Chat_Panel2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Chat_Panel2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chat2 = ui_Small_Label_create(ui_Chat_Panel2);
    lv_obj_set_width(ui_Chat2, lv_pct(100));
    lv_obj_set_height(ui_Chat2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Chat2, 1);
    lv_obj_set_y(ui_Chat2, 0);
    lv_obj_set_align(ui_Chat2, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_Chat2, "Chào Bạn ");
    lv_obj_set_style_text_color(ui_Chat2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chat2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chat2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chat_Icon2 = lv_image_create(ui_C2);
    lv_image_set_src(ui_Chat_Icon2, &ui_img_chatbox2_png);
    lv_obj_set_width(ui_Chat_Icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Chat_Icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Chat_Icon2, 0);
    lv_obj_set_y(ui_Chat_Icon2, 80);
    lv_obj_set_align(ui_Chat_Icon2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Chat_Icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Chat_Icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Chat_Icon2, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Chat_Icon2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scrolldots2 = ui_Scrolldots_create(ui_Chat);
    lv_obj_set_x(ui_Scrolldots2, 0);
    lv_obj_set_y(ui_Scrolldots2, -8);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D1), 4);

    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D2), 10);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D2), 0);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), 8);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), 8);
    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), 21);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), lv_color_hex(0x101C52),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Scrolldots2, UI_COMP_SCROLLDOTS_D3), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Chat, ui_event_Chat, LV_EVENT_ALL, NULL);

}

void ui_Chat_screen_destroy(void)
{
    if(ui_Chat) lv_obj_del(ui_Chat);

    // NULL screen variables
    ui_Chat = NULL;
    ui_Chat_container = NULL;
    ui_Chat_date = NULL;
    ui_C1 = NULL;
    ui_Chat_Panel1 = NULL;
    ui_Chat1 = NULL;
    ui_Chat_Icon1 = NULL;
    ui_C2 = NULL;
    ui_Chat_Panel2 = NULL;
    ui_Chat2 = NULL;
    ui_Chat_Icon2 = NULL;
    ui_Scrolldots2 = NULL;

}
